export const RepoActionTypes = {
  FETCH_REPOS_PENDING: "FETCH_REPOS_PENDING",
  FETCH_REPOS_FULFILLED: "FETCH_REPOS_FULFULLED",
  FETCH_REPOS_REJECTED: "FETCH_REPOS_REJECTED",

  FETCH_CONTRIBUTORS_PENDING: "FETCH_CONTRIBUTORS_PENDING",
  FETCH_CONTRIBUTORS_FULFILLED: "FETCH_CONTRIBUTORS_FULFILLED",
  FETCH_CONTRIBUTORS_REJECTED: "FETCH_CONTRIBUTORS_REJECTED",

  TOGGLE_FILTER_DROPDOWN_HIDDEN: "TOGGLE_FILTER_DROPDOWN_HIDDEN",
  FILTER_REPOS_BY: "FILTER_REPOS_BY",
  FILTER_REPOS_BY_URL: "FILTER_REPOS_BY_URL",
  SORT_REPOS_BY: "SORT_REPOS_BY",
  SORT_REPOS_BY_URL: "SORT_REPOS_BY_URL",
  TOGGLE_SORTBY_DROPDOWN_HIDDEN: "TOGGLE_SORTBY_DROPDOWN_HIDDEN",
  FIRST_PAGE_DISPLAYED: "FIRST_PAGE_DISPLAYED",
  LAST_PAGE_DISPLAYED: "LAST_PAGE_DISPLAYED",
};