export const RepoActionTypes = {
  FETCHED_REPOS_SUCCEEDED: "FETCHED_REPOS_SUCCEEDED",
  TOGGLE_FILTER_DROPDOWN_HIDDEN: "TOGGLE_FILTER_DROPDOWN_HIDDEN",
  FILTER_REPOS_BY: "FILTER_REPOS_BY",
  FILTER_REPOS_BY_URL: "FILTER_REPOS_BY_URL",
  SORT_REPOS_BY: "SORT_REPOS_BY",
  SORT_REPOS_BY_URL: "SORT_REPOS_BY_URL",
  TOGGLE_SORTBY_DROPDOWN_HIDDEN: "TOGGLE_SORTBY_DROPDOWN_HIDDEN",
  FIRST_PAGE_DISPLAYED: "FIRST_PAGE_DISPLAYED",
  LAST_PAGE_DISPLAYED: "LAST_PAGE_DISPLAYED",
};